### ISSUE TITLE
request collaborators setting

### ISSUE THREAD

**Issue by LMouSoo** [jshlee/seoulCity#1]

**Comment by jshlee** [comment]
just fork and do PR

**Comment by LMouSoo** [comment]
it was empty repo, so i do not fork this repo

**Comment by LMouSoo** [comment]
일단, 먼저 여기에 업로드 해두었습니다. https://github.com/LMouSoo/seoulBMS
fork가 가능해지면 다시 업로드 하도록 하겠습니다..

**Comment by jshlee** [comment]
fork this
then upload code
then pull request

**Comment by LMouSoo** [comment]
![image](https://cloud.githubusercontent.com/assets/5020013/25782951/90b26156-338e-11e7-9496-0d5739fa8ed7.png)

disable fork button
I can fork another repo, but I can't do this
I think that reason is this empty repo

**Comment by jshlee** [comment]
ok you can fork now
